### PR TITLE
Fix faraday connectionfailed issue

### LINKED ISSUE #177: Faraday::Error::ConnectionFailed has moved since v1.0.0
I tried to update gems used in my github-pages project but the following error appeared when building my project: 

```
          1: from /Users/satoryu/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-github-metadata-2.12.1/lib/jekyll-github-metadata/client.rb:71:in `save_from_errors'
/Users/satoryu/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-github-metadata-2.12.1/lib/jekyll-github-metadata/client.rb:80:in `rescue in save_from_errors': uninitialized constant Faraday::Error::ConnectionFailed (NameError)
Did you mean?  Faraday::ConnectionFailed
```

As this error says, 

https://github.com/jekyll/github-metadata/blob/9353743dc9ad6de2f522923d57eb8eb00f87abf6/lib/jekyll-github-metadata/client.rb#L80

the error class `Faraday::Error::ConnectionFailed` has been promoted as one of siblings under `Faraday`. 

https://github.com/lostisland/faraday/blob/master/lib/faraday/error.rb

### PR DESCRIPTION
**Pull request by satoryu**
This pull-request is to close #177

### CODE REVIEW

**Comment by satoryu** [comment]
While all tests passed on Travis CI, some tests failed on Appvoyer. 
Is there anyone who give me hints to fix it?

**Comment by ashmaroli** [comment]
> Is there anyone who give me hints to fix it?

The failures were due to flaky tests. They have now passed when re-run.

File: lib/jekyll-github-metadata/client.rb [hunk 1]
```diff
@@ -68,6 +68,15 @@ def method_missing(method_name, *args, &block)
...
       end
 
+      # NOTE: Faraday's error classes has been promoted to under Faraday module from v1.0.0.
+      # This patch aims to prevent on locking specific version of Faraday.
+      FARADAY_FAILED_CONNECTION =
+        begin
+          Faraday::Error::ConnectionFailed
+        rescue NameError
+          Faraday::ConnectionFailed
+        end
```
Comment (satoryu) [inline lib/jekyll-github-metadata/client.rb]: @parkr this tries to detect whether `Faraday::Error::ConnectionFailed` works or not. This would prevents from locking specific version of Faraday. All tests passes for the both versions v0.17 and v1.0 of Faraday: [Build #517 - jekyll/github-metadata - Travis CI](https://travis-ci.org/jekyll/github-metadata/builds/633133752).

File: .travis.yml [hunk 2]
```diff
@@ -13,6 +13,10 @@ matrix:
       env: JEKYLL_VERSION=3.7.0
     - rvm: *latest_ruby
       env: JEKYLL_VERSION=4.0.0.pre.alpha1
+    - rvm: *latest_ruby
+      env: FARADAY_VERSION=0.17.3
+    - rvm: *latest_ruby
+      env: FARADAY_VERSION=1.0.0
```
Comment (ashmaroli) [inline .travis.yml]: Let us relax these constraints a bit since the `Gemfile` uses the `~>` operator. 
`~> 0.17.3` translates into `">= 0.17.3", "< 0.18.0"` and `~> 1.0.0` translates into `">= 1.0.0", "< 1.1.0"`

Instead, having `~> 0.17` and `~> 1.0` will be future-proof and shall always test with the latest available version in the `v0.x` and `v1.x` series..

Comment (ashmaroli) [reply .travis.yml]: On further thought, I feel this should be clubbed with Jekyll versions..:
```yaml
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=3.7 FARADAY_VERSION=0.17
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=3.7 FARADAY_VERSION=1.0
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=4.0 FARADAY_VERSION=0.17
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=4.0 FARADAY_VERSION=1.0
```
And also have similar set up for AppVeyor builds as well.

Comment (satoryu) [reply .travis.yml]: @ashmaroli thanks! I did it.

File: .travis.yml [hunk 3]
```diff
@@ -10,13 +10,13 @@ rvm:
...
   include:
     - rvm: *latest_ruby
-      env: JEKYLL_VERSION=3.7.0
+      env: JEKYLL_VERSION=3.7.0 FARADAY_VERSION=0.17
     - rvm: *latest_ruby
-      env: JEKYLL_VERSION=4.0.0.pre.alpha1
+      env: JEKYLL_VERSION=3.7.0 FARADAY_VERSION=1.0
     - rvm: *latest_ruby
-      env: FARADAY_VERSION=0.17.3
+      env: JEKYLL_VERSION=4.0.0.pre.alpha1 FARADAY_VERSION=0.17
```
Comment (DirtyF) [inline .travis.yml]: should be `JEKYLL_VERSION=4.0.0` now

File: .travis.yml [hunk 4]
```diff
@@ -10,13 +10,13 @@ rvm:
...
     - rvm: *latest_ruby
-      env: FARADAY_VERSION=1.0.0
+      env: JEKYLL_VERSION=4.0.0.pre.alpha1 FARADAY_VERSION=1.0
```
Comment (DirtyF) [inline .travis.yml]: same here we want to test with `JEKYLL_VERSION=4.0.0`

File: .travis.yml (hunk 3 above)
Comment (ashmaroli) [reply .travis.yml]: @DirtyF This is an outdated diff.. The branch is already set up to test the latest versions.

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix

**Comment by ashmaroli** [comment]
Thank you for your contribution @satoryu 
@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
Thank you for your contribution @satoryu.

@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
Thank you for your contribution @satoryu.

@jekyllbot: merge +dev
